### ISSUE TITLE
[REQUEST] em3587 ncp uart fw

### ISSUE THREAD

**Issue by sgufa** [grobasoz/zigbee-firmware#14]
Hi. Would it be possible to add etrx3587-lr (EM3587) ncp uart with sw flow control firmware ebl?

**Comment by grobasoz** [comment]
What baud rate?
Do you know the port pin used to enable the PA/LNA?
Thanks :)

**Comment by grobasoz** [comment]
I have added the firmware to the repository. I used 115k2 Baud, ad PC6 for PA/LNA.

**Comment by sgufa** [comment]
Hi, i don't know the pin to enable PA/LNA. Actually i'm using the telegesis firmware (R309 AT commands) and no pin other than PB1 for TX, PB2 for RX and PA5 to trigger bootloader mode.
What the PA/LNA firmware is used for? Is it really necessary?
BTW thank you for the fw

**Comment by MattWestb** [comment]
I dont knowing if its designed as Silabs WSTK board or the Telegesis module.
Manual for the last https://fccid.io/S4GEM358L/User-Manual/User-Manual-2267485.iframe

One PM on the module pads:
- {1}  Pins  PB0  and  PC5  of  the  EM357  are  used  internally  to  control  the  front-end  module.    PB0  is  not available to the user.

- 2. Greta to here that you is is not in 110% lock-down Gary !!!!

**Comment by grobasoz** [comment]
ETRX3587-LR(S) is a "Long Range" device with an added PA/LNA with PC5 used as the enable for the FEM. I used PC6 so will need to modify the firmware :( I used the default settings from Silabs which uses PC6 for FEM control?
@MattWestb - Where I live, no Covid, no lockdowns :) Family double vax'd. BUT borders opening 17th Dec so things will change :(

**Comment by grobasoz** [comment]
I have modified the code to support PC5 for the PA/LNA. No bootloading on PA5 - did you want it? NCP supports bootload commands via software command.

**Comment by sgufa** [comment]
> I have modified the code to support PC5 for the PA/LNA. No bootloading on PA5 - did you want it? NCP supports bootload commands via software command.

Thank you. No need for PA5. Do you confirm it works well also with non LR version?
