### ISSUE TITLE
Question about ZBBridge firmware 6.10.3

### ISSUE THREAD

**Issue by r-vit** [grobasoz/zigbee-firmware#18]
I tried to flash NCP_USW_115k2_ZBBridge_6103.gbl firmware using standard Tasmota firmware update interface, but every time the process failed. At the same time flashing the older version from https://github.com/arendst/Tasmota/tree/development/tools/fw_SonoffZigbeeBridge_ezsp worked well. 

Is there some trick to flash 6.10.3 to ZBBridge?

**Comment by MattWestb** [comment]
Sonoff ZBB is needing one signed firmware or its not flashing the file on the device so only original firmware is working from SonOff (if not have flashing it withit  with SWD).

**Comment by r-vit** [comment]
Ah, ok. I do have a J-Link adapter, so I guess it will be the only way to flash the newer firmware.
Thank you.

**Comment by MattWestb** [comment]
SonOff have released little newer signed firmware but not six ten https://github.com/xsp1989/zigbeeFirmware/tree/master/firmware/ZigbeeBridge_SM-011 but perhaps its coming one, you never knowing ;-)

**Comment by r-vit** [comment]
Oh, nice! Thank you, I'll wait for the official one before trying to upgrade it manually. 
Closing the issue now, thanks again for your help.
