### ISSUE TITLE
Silabs Zigbee EmberZNet SDK 7.0.2.0 (7.0.2) GA bug-fix release from March 9, 2022

### ISSUE THREAD

**Issue by Hedda** [grobasoz/zigbee-firmware#29]
Silicon Labs released EmberZNet Zigbee 7.0.2.0 (7.0.2) for general availability and like to request a such firmware image for EFR32MG21

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-7.0.2.0.pdf

**Comment by grobasoz** [comment]
@Hedda - not too sure what that release is about? It's quite old... and had a few bugs...

**Comment by Hedda** [comment]
7.0.2 is bug-fix release to replace 7.0.1 which can not simply be replaced with 7.1.x since it is not as backwards compatible as 7.0.x
