### ISSUE TITLE
Building and compiling EmberZNet Zigbee firmware images via "SLC-CLI" command line tool without have a registered development kit board?

### ISSUE THREAD

**Issue by Hedda** [grobasoz/zigbee-firmware#30]
@grobasoz @MattWestb Any throughs on this? -> https://github.com/zigpy/zigpy/discussions/1042

**Comment by grobasoz** [comment]
Haven't used it - I'm happy with doing development using Simplicity Studio and IAR EWARM compiler...

**Comment by Hedda** [comment]
I guess it could be beneficial even if registration is needed as could publish a batch file with batch script on GitHub for building and compiling "standard community firmware images" so commands could be shared within the open source home automation communities. 

That could be somewhat similar to how Koenkk shared patches and compilation instructions for Z-Stack ZNP firmware:

https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0

https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0

**Comment by grobasoz** [comment]
I've managed to install slc-cli and generate some sample apps and build them (IAR as well)... 
So - seems to be viable... just need a means to create a "base app" to generate other apps from... may have to do some "light reading" :)
