### ISSUE TITLE
Which firmware image for EFR32MG13/EFR32MG13P based adapters like Tuya TYZS13 module and Elelabs ELR023 or ELU013?

### ISSUE THREAD

**Issue by Hedda** [grobasoz/zigbee-firmware#33]
Which bootloader and NCP firmware are used for EFR32MG13 adapters like Tuya TYZS13 module and Elelabs ELR023 or ELU013?

TYZS13 Module Datasheet says that it used EFR32MG13P732F512GM48 (i.e. EFR32MG13P) with 512 kB Flash Storage.

https://developer.tuya.com/en/docs/iot/tyzs13-module-datasheet?id=K98u373pszqe3

Is this the same EFR32MG13P SoC that Elelabs Zigbee USB Adapter ELU013 and Elelabs Zigbee Raspberry Pi Shield ELR023 uses?

https://elelabs.com/products/elelabs-usb-adapter.html

https://elelabs.com/products/elelabs-zigbee-shield.html

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/tree/master/data/EFR32MG13

# efr32mg13p

https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

### efr32mg1b-bootloader
* EFR32MG13P target
* Standalone Bootloader
* NCP UART TX --> PA0
* NCP UART RC <-- PA1
* Version: 1.10.3
* DCDC bypass

### efr32mg13p-v8-678-sw-115200
* EFR32MG13P target
* NCP Software flow control, 115200 baudrate
* NCP UART TX --> PA0
* NCP UART RC <-- PA1
* EZSP Version 8
* EmberZNet 6.7.8
* DCDC bypass

<html>
<body>

Configuration Parameter | Value
-- | --
Address Table Size | 16
Child Table Size | 32
Source Routes | 200

</body>
</html>

# Use case

Among other products, Tuya TYZS13 module is used in Tuya T6E Android-based panels which have now been hacked by [blakadder ](https://github.com/blakadder)to run Zigbee2MQTT directly but that first require you to reflash the Zigbee adapter:

https://blakadder.com/t6e-z2m/

https://community.home-assistant.io/t/tuya-t6e-4-inch-control-panel-for-ccs-central-control-system-android-based-in-wall-4-inch-smart-display-with-touch-screen-now-sold-under-many-different-brands/473366

[blakadder ](https://github.com/blakadder) has also hacked ITead's Sonoff NSPanel Pro (which looks to be a rebranded Tuya T6E) the same way by to run Zigbee2MQTT by getting the ADB access that is needed:

https://blakadder.com/nspanel-pro-sideload/

https://community.home-assistant.io/t/sonoff-nspanel-pro-android-based-in-wall-4-inch-smart-display-with-touch-screen-by-itead-available-for-pre-order/448841

**Comment by MattWestb** [comment]
The tuya module is using one normal NCP bootloader and can rebooting by software command to it (we have prof of concept posted by user) and if tuya have putting boot pin is not known but is likely then its recommended in most tuya Zigbe NCP dev papers.
